MEMORIES = {
    "pic1": "Class 12 School picnic",
    "pic2": "First date?",
    "pic3": "School farewell",
    "pic4": "Niche se upar tak promotion....",
    "pic5": "Diwali at home",
    "pic6": "Just how fast the night changes....",
    "pic7": "Marbella's aesthetics",
    "pic8": "South city date",
    "pic9": "One where you looked better than the aesthetic cafe",
    "pic10": "Sorry for what happened this evening :)",
    "pic11": "Snacking date where I didnt shave",
    "pic12": "Three of us twinning in white (3rd: your teeth)",
    "pic13": "Usual home date",
    "pic14": "Durga puja where I pissed you off with public transport",
    "pic15": "One of my favorite kurtis",
    "pic16": "Just kept it coz we looked great in whites",
    "pic17": "Average food at Mocambo but we looked great",
    "pic18": "One where Aanchal came to Pilani?!",
    "pic19": "JW Marriott Puja date",
    "pic20": "Delta suites, PC: Ankita",
    "pic21": "We look adorable!",
    "pic22": "Eve date with my girl!",
    "pic23": "Cant keep our hands off each other!",
    "pic24": "Siddhivinayak ji would be proud of us!",
    "pic25": "Cant keep our hands off each other! (2)",
    "pic26": "Made it to your graduation with your entire family!",
    "pic27": "The most gorgeous doctor I've ever seen",
    "pic28": "Don't we look married already?",
    "pic29": "Can't keep our hands off each other! (3)",
    "pic30": "First movie date and I'm obsessed with you",
    "pic31": "Again, average cafe but you looked stunning",
    "pic32": "Cant keep our hands off each other! (4)"
}